# Generated by Django 4.2.6 on 2023-11-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Brother's Name")),
                ('age', models.FloatField(null=True, verbose_name="Brother's Age (optional)")),
                ('about', models.TextField(null=True, verbose_name='About Brother (optional)')),
                ('img', models.ImageField(upload_to='brothers', verbose_name="Brother's Image")),
            ],
        ),
    ]
