# Generated by Django 4.1.7 on 2023-12-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='arts')),
            ],
        ),
    ]
