# Generated by Django 4.1.7 on 2023-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0003_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='brothers_title',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='retreat_center_title',
        ),
    ]
